### PR TITLE
Fix `ImportError: cannot import name Args`

### PR DESCRIPTION
**Pull request by blueyed**
Traceback (most recent call last):
      File "…/usr/bin/legit", line 4, in <module>
        import legit.cli
      File "…/lib/legit/legit/cli.py", line 16, in <module>
        from clint import Args

Ref: https://github.com/kennethreitz/legit/pull/130
Ref: https://github.com/kennethreitz/legit/pull/131

### CODE REVIEW

**Comment by realhu1989** [comment]
pip uninstall clint
pip install clint==0.3.1

It worked on my ubuntu.

**Comment by mastito03** [comment]
when I run 
`pip uninstall clint`

it say
`Not uninstalling clint at /usr/lib/python2.7/dist-packages, owned by OS`

I'm using ubuntu 14.04

**Comment by hickford** [comment]
@mastito03 try `sudo pip uninstall clint`. Read https://help.ubuntu.com/community/RootSudo

**Comment by mastito03** [comment]
@hickford it still say `Not uninstalling clint at /usr/lib/python2.7/dist-packages, owned by OS` when i run with `sudo`

**Comment by hickford** [comment]
Oh maybe the package manager put it there . Try `apt-get remove python-clint`

http://packages.ubuntu.com/trusty/python/python-clint

**Comment by wkentaro** [comment]
maybe you have installed legit via apt?
if so pip cannot uninstall it.

you can check it by

dpkg --get-selections | grep legit

and uninstall by

sudo aptitude purge legit

2015年11月3日火曜日、Benedictus Arya<notifications@github.com>さんは書きました:

> @hickford <https://github.com/hickford> it still say Not uninstalling
> clint at /usr/lib/python2.7/dist-packages, owned by OS when i run with
> sudo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kennethreitz/legit/pull/139#issuecomment-153097854>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
oh same solution by @hickford

**Pull request merged**
