### PR TITLE
Add the packaging metadata to build the legit snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that will work in most Linux distributions.
Landing it upstream will enable to push builds to the Ubuntu store, and get updated versions to many users.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

I was just using legit to test one of the new features of snapcraft. And it worked nicely, so I thought sending it upstream to see if you would like to publish snaps for it.

You can find more information about snapcraft here: http://snapcraft.io/

To build it in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ sudo snap install core  # Required to link using the classic interface, what I was just testing.
    $ git clone https://github.com/elopio/legit
    $ cd legit
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous --classic

If you have any questions or comments, please let me know.

**Comment by weakish** [comment]
@elopio Current the repo does not contain anything for packaging
(except for pip of course).
You can create a separate repo for snap, or contribute to repos collecting snap packaging metadata.

**Comment by elopio** [comment]
@weakish the idea of snapcraft is to be very lightweight and secure, and fully automated as part of your CI, so it can be maintained directly by upstreams and delivered directly to users as soon as you make a tag in github.
I can understand if you are not interested in publishing it in the Ubuntu store at the moment. Just let me know if you get interested later.

pura vida.

**Comment by weakish** [comment]
> if you are not interested in publishing it in the Ubuntu store

@elopio I am just a contributor. The maintainer is @kennethreitz 

Related issue: #17

**Pull request closed without merging**
