### PR TITLE
Add manpage generated from README via ronn

### PR DESCRIPTION
**Pull request by wkentaro**
For #47

### CODE REVIEW

**Comment by wkentaro** [comment]
By `$ man legit`

screen shot 2015-08-30 at 5 51 17 pm

**Comment by hickford** [comment]
It's installed automatically? Neat

**Comment by wkentaro** [comment]
Not installed automatically same as completion files.
So we need line for homebrew like:
https://github.com/Homebrew/homebrew/pull/43406/files

**Comment by wkentaro** [comment]
After changing README.rst, the man/legit.1 should be updated via:

```
$ python setup.py build_manpage
```

**Comment by hickford** [comment]
Cool. Is it possible to ship the man page with the Python package `pip install legit`?

**Comment by wkentaro** [comment]
I'm trying that at:
https://github.com/kennethreitz/legit/pull/192

**Pull request merged**
