### PR TITLE
Crash on indexed lookup with the filter iterator

### PR DESCRIPTION
**Pull request by erikdejonge**
In python3 filter returns an iterator, added a cast to a list to prevent crashing of line 119-120

### CODE REVIEW

**Comment by kennethreitz** [comment]
is this for Python 3?

Python 3 is not an active target for this project, as the primary deliverable is a compiled/bundled executable. But, no harm in fixing a bug certainly :)

**Comment by erikdejonge** [comment]
Oh, i'm using it in python3 now. This was the only thing i encountered 👍 

The filter method returns an iterator instead of the collection in py3

python2:
```
>>> filter(lambda x:x==4, range(0,10))
[4]

```
python3:
```
>>> filter(lambda x:x==4, range(0,10))
<filter object at 0x101ce9b00>
>>> list(filter(lambda x:x==4, range(0,10)))
[4]

```

**Comment by erikdejonge** [comment]
Sorry, i included 'merge.sh' in the pull request, that's not needed, my bad.

**Comment by weakish** [comment]
Cherry-picked in 39a137a4632361faf5f5d80ec1e072decdc10944

**Pull request closed without merging**
